SRC=project_main.c\
src/sum.c\
src/sub.c\
src/mul.c\
src/mod.c\
src/fact.c\
test/test_operations.c\
unity/unity.c\

INC=-Iinc\
-Itest\
-Iunity



all:
	gcc $(SRC) $(INC) -o amit.exe

clean:
	rm -r *.exe

